SELECT Count(*) AS counts, 'Product      ' AS DATA_TYPE, rej_ind,COL_NAME, testcase_RULE_NAME, CYC_DT FROM ENTPRMT_BHI_extract.FAIL_QA_PROD WHERE rej_ind = 'Y' AND CYC_DT >= Add_Months(Current_Date, -12) GROUP BY 2,3,4,5,6 UNION ALL		
SELECT Count(*) AS counts, 'PCC' AS DATA_TYPE, rej_ind ,COL_NAME, testcase_RULE_NAME, CYC_DT FROM ENTPRMT_BHI_extract.FAIL_QA_PROD_CLIENT_CONTR WHERE rej_ind = 'Y' AND CYC_DT >= Add_Months(Current_Date, -12) GROUP BY 2,3,4,5,6 UNION ALL		
SELECT Count(*) AS counts, 'MBR' AS DATA_TYPE, rej_ind ,COL_NAME, testcase_RULE_NAME, CYC_DT FROM ENTPRMT_BHI_extract.FAIL_QA_MBR WHERE rej_ind = 'Y' AND CYC_DT >= Add_Months(Current_Date, -12) GROUP BY 2,3,4,5,6 UNION ALL		
SELECT Count(*) AS counts,'PFO' AS DATA_TYPE,  rej_ind ,COL_NAME, testcase_RULE_NAME, CYC_DT FROM ENTPRMT_BHI_extract.FAIL_QA_PFO_CLM WHERE rej_ind = 'Y' AND CYC_DT >= Add_Months(Current_Date, -12) GROUP BY 2,3,4,5,6 UNION ALL		
SELECT Count(*) AS counts,'INP_CLM_HDR' AS DATA_TYPE,rej_ind ,COL_NAME, testcase_RULE_NAME, CYC_DT FROM ENTPRMT_bhi_extract.FAIL_QA_INP_CLM_HDR WHERE rej_ind = 'Y' AND CYC_DT >= Add_Months(Current_Date, -12) GROUP BY 2,3,4,5,6 UNION ALL		
SELECT Count(*) AS counts,'INP_CLM_LN' AS DATA_TYPE, rej_ind ,COL_NAME, testcase_RULE_NAME, CYC_DT FROM ENTPRMT_BHI_extract.FAIL_QA_INP_CLM_LI WHERE rej_ind = 'Y' AND CYC_DT >= Add_Months(Current_Date, -12) GROUP BY 2,3,4,5,6 UNION ALL		
SELECT Count(*) AS counts,'PHARM' AS DATA_TYPE, rej_ind ,COL_NAME, testcase_RULE_NAME, CYC_DT FROM ENTPRMT_BHI_extract.FAIL_QA_PHARMACY_CLM WHERE rej_ind = 'Y' AND CYC_DT >= Add_Months(Current_Date, -12) GROUP BY 2,3,4,5,6 		
ORDER BY 2,6,3; 		
SELECT Count(*) AS counts, 'PCC' AS DATA_TYPE, rej_ind ,COL_NAME, testcase_RULE_NAME, CYC_DT FROM ENTPRIL_BHI_extract.FAIL_QA_PROD_CLIENT_CONTR WHERE rej_ind = 'Y' AND CYC_DT >= Add_Months(Current_Date, -12) GROUP BY 2,3,4,5,6 UNION ALL
SELECT Count(*) AS counts, 'MBR' AS DATA_TYPE, rej_ind ,COL_NAME, testcase_RULE_NAME, CYC_DT FROM ENTPRIL_BHI_extract.FAIL_QA_MBR WHERE rej_ind = 'Y' AND CYC_DT >= Add_Months(Current_Date, -12) GROUP BY 2,3,4,5,6 UNION ALL
SELECT Count(*) AS counts,'PFO' AS DATA_TYPE,  rej_ind ,COL_NAME, testcase_RULE_NAME, CYC_DT FROM ENTPRIL_BHI_extract.FAIL_QA_PFO_CLM WHERE rej_ind = 'Y' AND CYC_DT >= Add_Months(Current_Date, -12) GROUP BY 2,3,4,5,6 UNION ALL
SELECT Count(*) AS counts,'INP_CLM_HDR' AS DATA_TYPE,rej_ind ,COL_NAME, testcase_RULE_NAME, CYC_DT FROM ENTPRIL_bhi_extract.FAIL_QA_INP_CLM_HDR WHERE rej_ind = 'Y' AND CYC_DT >= Add_Months(Current_Date, -12) GROUP BY 2,3,4,5,6 UNION ALL
SELECT Count(*) AS counts,'INP_CLM_LN' AS DATA_TYPE, rej_ind ,COL_NAME, testcase_RULE_NAME, CYC_DT FROM ENTPRIL_BHI_extract.FAIL_QA_INP_CLM_LI WHERE rej_ind = 'Y' AND CYC_DT >= Add_Months(Current_Date, -12) GROUP BY 2,3,4,5,6 UNION ALL
SELECT Count(*) AS counts,'PHARM' AS DATA_TYPE, rej_ind ,COL_NAME, testcase_RULE_NAME, CYC_DT FROM ENTPRIL_BHI_extract.FAIL_QA_PHARMACY_CLM WHERE rej_ind = 'Y' AND CYC_DT >= Add_Months(Current_Date, -12) GROUP BY 2,3,4,5,6 
ORDER BY 2,6,3; 
SELECT Count(*) AS counts, 'Product      ' AS DATA_TYPE, rej_ind,COL_NAME, testcase_RULE_NAME, CYC_DT FROM ENTPRNM_BHI_extract.FAIL_QA_PROD WHERE rej_ind = 'Y' AND CYC_DT >= Add_Months(Current_Date, -12) GROUP BY 2,3,4,5,6 UNION ALL
SELECT Count(*) AS counts, 'PCC' AS DATA_TYPE, rej_ind ,COL_NAME, testcase_RULE_NAME, CYC_DT FROM ENTPRNM_BHI_extract.FAIL_QA_PROD_CLIENT_CONTR WHERE rej_ind = 'Y' AND CYC_DT >= Add_Months(Current_Date, -12) GROUP BY 2,3,4,5,6 UNION ALL
SELECT Count(*) AS counts, 'MBR' AS DATA_TYPE, rej_ind ,COL_NAME, testcase_RULE_NAME, CYC_DT FROM ENTPRNM_BHI_extract.FAIL_QA_MBR WHERE rej_ind = 'Y' AND CYC_DT >= Add_Months(Current_Date, -12) GROUP BY 2,3,4,5,6 UNION ALL
SELECT Count(*) AS counts,'PFO' AS DATA_TYPE,  rej_ind ,COL_NAME, testcase_RULE_NAME, CYC_DT FROM ENTPRNM_BHI_extract.FAIL_QA_PFO_CLM WHERE rej_ind = 'Y' AND CYC_DT >= Add_Months(Current_Date, -12) GROUP BY 2,3,4,5,6 UNION ALL
SELECT Count(*) AS counts,'INP_CLM_HDR' AS DATA_TYPE,rej_ind ,COL_NAME, testcase_RULE_NAME, CYC_DT FROM ENTPRNM_bhi_extract.FAIL_QA_INP_CLM_HDR WHERE rej_ind = 'Y' AND CYC_DT >= Add_Months(Current_Date, -12) GROUP BY 2,3,4,5,6 UNION ALL
SELECT Count(*) AS counts,'INP_CLM_LN' AS DATA_TYPE, rej_ind ,COL_NAME, testcase_RULE_NAME, CYC_DT FROM ENTPRNM_BHI_extract.FAIL_QA_INP_CLM_LI WHERE rej_ind = 'Y' AND CYC_DT >= Add_Months(Current_Date, -12) GROUP BY 2,3,4,5,6 UNION ALL
SELECT Count(*) AS counts,'PHARM' AS DATA_TYPE, rej_ind ,COL_NAME, testcase_RULE_NAME, CYC_DT FROM ENTPRNM_BHI_extract.FAIL_QA_PHARMACY_CLM WHERE rej_ind = 'Y' AND CYC_DT >= Add_Months(Current_Date, -12) GROUP BY 2,3,4,5,6 
ORDER BY 2,6,3; 
SELECT Count(*) AS counts, 'Product      ' AS DATA_TYPE, rej_ind,COL_NAME, testcase_RULE_NAME, CYC_DT FROM ENTPROK_BHI_extract.FAIL_QA_PROD WHERE rej_ind = 'Y' AND CYC_DT >= Add_Months(Current_Date, -12) GROUP BY 2,3,4,5,6 UNION ALL
SELECT Count(*) AS counts, 'PCC' AS DATA_TYPE, rej_ind ,COL_NAME, testcase_RULE_NAME, CYC_DT FROM ENTPROK_BHI_extract.FAIL_QA_PROD_CLIENT_CONTR WHERE rej_ind = 'Y' AND CYC_DT >= Add_Months(Current_Date, -12) GROUP BY 2,3,4,5,6 UNION ALL
SELECT Count(*) AS counts, 'MBR' AS DATA_TYPE, rej_ind ,COL_NAME, testcase_RULE_NAME, CYC_DT FROM ENTPROK_BHI_extract.FAIL_QA_MBR WHERE rej_ind = 'Y' AND CYC_DT >= Add_Months(Current_Date, -12) GROUP BY 2,3,4,5,6 UNION ALL
SELECT Count(*) AS counts,'PFO' AS DATA_TYPE,  rej_ind ,COL_NAME, testcase_RULE_NAME, CYC_DT FROM ENTPROK_BHI_extract.FAIL_QA_PFO_CLM WHERE rej_ind = 'Y' AND CYC_DT >= Add_Months(Current_Date, -12) GROUP BY 2,3,4,5,6 UNION ALL
SELECT Count(*) AS counts,'INP_CLM_HDR' AS DATA_TYPE,rej_ind ,COL_NAME, testcase_RULE_NAME, CYC_DT FROM ENTPROK_bhi_extract.FAIL_QA_INP_CLM_HDR WHERE rej_ind = 'Y' AND CYC_DT >= Add_Months(Current_Date, -12) GROUP BY 2,3,4,5,6 UNION ALL
SELECT Count(*) AS counts,'INP_CLM_LN' AS DATA_TYPE, rej_ind ,COL_NAME, testcase_RULE_NAME, CYC_DT FROM ENTPROK_BHI_extract.FAIL_QA_INP_CLM_LI WHERE rej_ind = 'Y' AND CYC_DT >= Add_Months(Current_Date, -12) GROUP BY 2,3,4,5,6 UNION ALL
SELECT Count(*) AS counts,'PHARM' AS DATA_TYPE, rej_ind ,COL_NAME, testcase_RULE_NAME, CYC_DT FROM ENTPROK_BHI_extract.FAIL_QA_PHARMACY_CLM WHERE rej_ind = 'Y' AND CYC_DT >= Add_Months(Current_Date, -12) GROUP BY 2,3,4,5,6
ORDER BY 2,6,3; 
SELECT Count(*) AS counts, 'MBR' AS DATA_TYPE, rej_ind ,COL_NAME, testcase_RULE_NAME,CYC_DT FROM ENTPRTX_BHI_extract.FAIL_QA_MBR WHERE rej_ind = 'Y' AND CYC_DT >= Add_Months(Current_Date, -12) GROUP BY 2,3,4,5,6 UNION ALL                       
SELECT Count(*) AS counts,'PFO' AS DATA_TYPE,  rej_ind ,COL_NAME, testcase_RULE_NAME,CYC_DT FROM ENTPRTX_BHI_extract.FAIL_QA_PFO_CLM WHERE rej_ind = 'Y' AND CYC_DT >= Add_Months(Current_Date, -12) GROUP BY 2,3,4,5,6 UNION ALL                       
SELECT Count(*) AS counts,'INP_CLM_HDR' AS DATA_TYPE,rej_ind ,COL_NAME, testcase_RULE_NAME,CYC_DT FROM ENTPRTX_bhi_extract.FAIL_QA_INP_CLM_HDR WHERE rej_ind = 'Y' AND CYC_DT >= Add_Months(Current_Date, -12) GROUP BY 2,3,4,5,6 UNION ALL                       
SELECT Count(*) AS counts,'INP_CLM_LN' AS DATA_TYPE, rej_ind ,COL_NAME, testcase_RULE_NAME,CYC_DT FROM ENTPRTX_BHI_extract.FAIL_QA_INP_CLM_LI WHERE rej_ind = 'Y' AND CYC_DT >= Add_Months(Current_Date, -12) GROUP BY 2,3,4,5,6 UNION ALL                       
SELECT Count(*) AS counts,'PHARM' AS DATA_TYPE, rej_ind ,COL_NAME, testcase_RULE_NAME,CYC_DT FROM ENTPRTX_BHI_extract.FAIL_QA_PHARMACY_CLM WHERE rej_ind = 'Y' AND CYC_DT >= Add_Months(Current_Date, -12) GROUP BY 2,3,4,5,6 
ORDER BY 2,6,3; 
